name: Prettier Check and Translation Files Check

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  prettier-check-and-translation-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: 'frontend' # Path to your frontend folder

      - name: Install Prettier
        run: npm install --global prettier

      - name: Run Prettier
        working-directory: ${{ github.workspace }}/frontend # Use absolute path to frontend directory
        run: npx prettier --write .

      - name: Check Translation Files
        working-directory: ${{ github.workspace }}/frontend # Use absolute path to frontend directory
        run: |
          if [[ $(git rev-parse --verify HEAD^ 2>/dev/null) ]]; then
            CHANGED_FILES=$(git diff --name-only HEAD^ src/locales/en/common.json)
            if [ "$CHANGED_FILES" ]; then
              for lang in ar bg de es fr ru; do
                if [ -f "$${{ github.workspace }}/frontend/src/locales/$lang/common.json" ]; then
                  missing_keys=$(jq -s 'reduce .[] as $item (.[1] | keys_unsorted as $keys | .[0]; .[1]) | reduce $keys[] as $key ([]; if .[0][$key] == null then . + [$key] else . end) | .[]' "$${{ github.workspace }}/frontend/src/locales/en/common.json" "$${{ github.workspace }}/frontend/src/locales/$lang/common.json")
                  if [ "$missing_keys" ]; then
                    echo "Missing keys in $lang translation file: $missing_keys"
                    exit 1
                  fi
                else
                  echo "Translation file for $lang does not exist."
                fi
              done
            fi
          else
            echo "Initial commit, skipping translation files check."
          fi
