name: Prettier Check and Translation Files Check

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  prettier-check-and-translation-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: 'frontend' # Path to your frontend folder

      - name: Install dependencies
        working-directory: frontend # Change to the frontend directory
        run: npm install

      - name: Run Prettier
        working-directory: frontend # Change to the frontend directory
        run: npx prettier --check .

      - name: Check Translation Files
        working-directory: frontend # Change to the frontend directory
        run: |
          # Check if there are any changes in the en translation file
          if [[ $(git diff --name-only HEAD^ src/locales/en/common.json) ]]; then
            # Loop through other language translation folders
            for lang in ar bg de es fr ru; do
              # Check if the corresponding translation file exists
              if [ -f "src/locales/$lang/common.json" ]; then
                # Compare keys between en and current language
                missing_keys=$(jq -s 'reduce .[] as $item (.[1] | keys_unsorted as $keys | .[0]; .[1]) | reduce $keys[] as $key ([]; if .[0][$key] == null then . + [$key] else . end) | .[]' src/locales/en/common.json "src/locales/$lang/common.json")
                if [ "$missing_keys" ]; then
                  echo "Missing keys in $lang translation file: $missing_keys"
                  exit 1
                fi
              else
                echo "Translation file for $lang does not exist."
              fi
            done
          fi
